# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = magic-from-hypr
  suppress_event = maximize
  match:class = .* # You'll probably like this.
}


# Fix some dragging issues with XWayland
windowrule {
  name = drag-issues
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Always run steam apps at specific workspace
# Doesn't work on native wayland fullscreen apps
windowrule {
  name = steam-apps
  workspace = 5 silent
  match:class = ^(steam_app_).*
}

# Ok then, let's launch ALL fullscreenapps at specific workspace (since I only launch games at fullscreen, it's ok) 
windowrule {
  name = fullscreen-apps
  workspace = 5
  match:fullscreen = 1
}

# no screenshare for some apps
windowrule {
    name = no-screen-share
    no_screen_share = on
    match:class = (org.keepassxc.KeePassXC|org.telegram.desktop)
}

# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, monitor:desc:Dell Inc. DELL P2418D MY3ND9CN0YBT
workspace = 2, monitor:desc:Dell Inc. DELL P2418D MY3ND9CN0YBT
workspace = 3, monitor:desc:Dell Inc. DELL P2418D MY3ND9CN0NTT
workspace = 4, monitor:desc:Dell Inc. DELL P2418D MY3ND9CN0NTT
workspace = 5, monitor:desc:Dell Inc. DELL P2418D MY3ND9CN0NTT
workspace = 6, monitor:0
